# Generated by Django 3.2.7 on 2021-10-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='plan',
            new_name='plan_days',
        ),
    ]
